import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const uri=s=>'data:text/javascript;base64,'+Buffer.from(s).toString('base64');
const shared=uri(ts.transpileModule(readFileSync('app/lib/ack-shared.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
const runtime=uri('export const getRuntimeEnv=()=>globalThis.__ackTestEnv;');
const directory=uri(`export class PortalError extends Error {constructor(message,status=400){super(message);this.status=status}}; export const configuredAdminEmails=()=>['admin@test.local'];`);
let source=ts.transpileModule(readFileSync('app/lib/ack-store.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace('import \'server-only\';','').replaceAll("'./runtime-env'",JSON.stringify(runtime)).replaceAll("'./directory-store'",JSON.stringify(directory)).replaceAll("'./ack-shared'",JSON.stringify(shared));
const store=await import(uri(source));const helpers=await import(shared);
function fixture(){const sql=new DatabaseSync(':memory:');sql.exec(`CREATE TABLE directory_groups(id INTEGER PRIMARY KEY,name TEXT);CREATE TABLE rehabilitation_centers(id INTEGER PRIMARY KEY,name TEXT);CREATE TABLE portal_users(id INTEGER PRIMARY KEY,email TEXT,name TEXT,role TEXT,role_label TEXT,zone TEXT,group_id INTEGER,center_id INTEGER,active INTEGER);INSERT INTO directory_groups VALUES(1,'Altabrisa');INSERT INTO portal_users VALUES(1,'leader@test.local','Persona de prueba','leader','Líder','Tiburón',1,NULL,1),(2,'other@test.local','Otra persona','leader','Líder','Tiburón',1,NULL,1);`);sql.exec(readFileSync('drizzle/0021_flippant_genesis.sql','utf8'));
 const prepare=query=>{let values=[];return {bind(...args){values=args;return this;},async first(){return sql.prepare(query).get(...values)||null;},async all(){return {results:sql.prepare(query).all(...values)};},async run(){const r=sql.prepare(query).run(...values);return {meta:{changes:r.changes,last_row_id:r.lastInsertRowid}};}}};
 const files=new Map();globalThis.__ackTestEnv={DB:{prepare,async batch(statements){sql.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sql.exec('COMMIT');return results;}catch(e){sql.exec('ROLLBACK');throw e;}}},BUCKET:{async put(key,bytes){files.set(key,bytes);},async delete(key){files.delete(key);},async get(key){return files.get(key);}}};return {sql,files};}
const admin={email:'admin@test.local',name:'Admin',role:'admin',active:true};const leader={email:'leader@test.local',name:'Persona de prueba',role:'leader',roleLabel:'Líder',zone:'Tiburón',groupId:1,active:true};const other={...leader,email:'other@test.local'};
const draft={action:'draft',title:'Documento de prueba técnica',zone:'Tiburón',category:'Junta',meetingDate:'2026-09-28',version:'1.0',content:'<h2>Acuerdo de prueba</h2><p>Contenido suficiente para comprobar la lectura y firma.</p>',requiresNew:true};
const strokes=[Array.from({length:12},(_,i)=>({x:30+i*10,y:50+i%3*10}))];const body={action:'confirm',fullName:'Persona de prueba',groupName:'Altabrisa',serviceRole:'Líder',zone:'Tiburón',read:true,communicate:true,strokes};
test('permissions, progress, signature, idempotency, unique folios, immutable history and version transitions',async()=>{const {sql,files}=fixture();
 await assert.rejects(()=>store.saveAckAdmin(leader,draft),e=>e.status===403);
 const first=await store.saveAckAdmin(admin,draft);assert.equal((await store.ackList(leader)).assignments.length,0);
 await store.saveAckAdmin(admin,{action:'publish',id:first.id,emails:[leader.email,other.email]});
 let own=(await store.ackList(leader)).assignments[0];const foreign=(await store.ackList(other)).assignments[0];
 await assert.rejects(()=>store.ackDocument(leader,foreign.id),e=>e.status===404);
 await assert.rejects(()=>store.confirmAck(admin,{...body,id:own.id}),e=>e.status===403);
 await assert.rejects(()=>store.confirmAck(leader,{...body,id:own.id}),/final/);
 await store.ackProgress(leader,{id:own.id,progress:100});
 await assert.rejects(()=>store.confirmAck(leader,{...body,id:own.id,read:false}),/obligatorias/);
 await assert.rejects(()=>store.confirmAck(leader,{...body,id:own.id,strokes:[]}),/firma/);
 const signed=await store.confirmAck(leader,{...body,id:own.id});assert.deepEqual(await store.confirmAck(leader,{...body,id:own.id}),signed);assert.equal(files.size,1);
 const receipt=await store.ackReceipt(leader,String(signed.id));assert.match(receipt.record.folio,/^ZT-JL-\d{8}-0001$/);assert.equal(receipt.record.version,'1.0');assert.equal(receipt.record.signature_key,undefined);
 await assert.rejects(()=>store.ackReceipt(other,String(signed.id)),e=>e.status===404);
 await store.ackProgress(other,{id:foreign.id,progress:100});const signed2=await store.confirmAck(other,{...body,id:foreign.id});assert.notEqual((await store.ackReceipt(other,String(signed2.id))).record.folio,receipt.record.folio);
 await assert.rejects(()=>store.saveAckAdmin(admin,{...draft,id:first.id,content:'Edited'}),e=>e.status===409);
 const documentId=own.document_id;const minor=await store.saveAckAdmin(admin,{...draft,documentId,version:'1.1',requiresNew:false});await store.saveAckAdmin(admin,{action:'publish',id:minor.id,emails:[leader.email]});
 const minorAssignment=(await store.ackList(leader)).assignments.find(a=>a.version_id===minor.id);assert.equal(minorAssignment.receipt_id,signed.id);assert.equal(minorAssignment.confirmed_version,'1.0');assert.equal((await store.ackReceipt(leader,String(signed.id))).record.version,'1.0');
 const major=await store.saveAckAdmin(admin,{...draft,documentId,version:'2.0'});await store.saveAckAdmin(admin,{action:'publish',id:major.id,emails:[leader.email]});
 const majorAssignment=(await store.ackList(leader)).assignments.find(a=>a.version_id===major.id);assert.equal(majorAssignment.receipt_id,null);
 await store.ackProgress(leader,{id:majorAssignment.id,progress:100});await store.saveAckAdmin(admin,{action:'archive',id:documentId});await assert.rejects(()=>store.confirmAck(leader,{...body,id:majorAssignment.id}),e=>e.status===409);
 assert.equal((await store.ackReceipt(leader,String(signed.id))).record.version,'1.0');assert.equal(sql.prepare('SELECT COUNT(*) n FROM acknowledgements').get().n,2);sql.close();
});
test('editor markup cannot expose executable content, and empty or invalid strokes are rejected',()=>{assert.equal(helpers.sanitizeEditorial('<h2 onclick="alert(1)">Título</h2><script>alert(1)</script><img src=x onerror=alert(1)><p>Texto</p>'),'<h2>Título</h2><p>Texto</p>');assert.equal(helpers.validStrokes([]),false);assert.equal(helpers.validStrokes([[{x:0,y:0}]]),false);assert.equal(helpers.validStrokes([[{x:NaN,y:1}]]),false);assert.equal(helpers.validStrokes(strokes),true);});
