'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {SubHeader,SubFooter} from '../section-shell';
import './exports.css';
type Section={id:string;title:string;category:string};
export default function ExportCenter({scope}:{scope:'admin'|'leader'}){
 const [sections,setSections]=useState<Section[]>([]),[selected,setSelected]=useState<string[]>([]),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){setError('');setLoading(true);try{const r=await fetch(`/api/exports?catalog=1&scope=${scope}`,{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudieron cargar las secciones.');setSections(data.sections);const initial=new URLSearchParams(window.location.search).get('section');if(initial&&data.sections.some((s:Section)=>s.id===initial))setSelected([initial]);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[scope]);
 const filtered=sections.filter(s=>`${s.title} ${s.category}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(search.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()));
 const groups=Array.from(new Set(filtered.map(s=>s.category)));
 async function download(ids:string[],format:'csv'|'zip'){
  if(!ids.length)return;setBusy(format==='csv'?ids[0]:'zip');setError('');setNotice('');
  try{const params=new URLSearchParams({scope,format});ids.forEach(id=>params.append('section',id));const response=await fetch('/api/exports?'+params,{cache:'no-store'});if(!response.ok){const data=await response.json();throw new Error(data.error||'No se pudo preparar la descarga.');}const blob=await response.blob();const filename=response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)?.[1]||`fgdll.${format}`;const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(href),60000);setNotice(`Archivo preparado: ${filename}. Revisa las descargas de tu navegador.`);}catch(e){setError((e as Error).message||'La descarga se interrumpió. Inténtalo de nuevo.');}finally{setBusy('');}
 }
 return <><SubHeader label="Descargas CSV"/><main className="exports-page"><Link href={scope==='admin'?'/administracion':'/lider'}>{scope==='admin'?'Administración':'Portal del Líder'}</Link><header className="exports-heading"><div><span className="exports-eyebrow">{scope==='admin'?'DATOS DEL PORTAL':'DATOS DE MI SERVICIO'}</span><h1>Centro de descargas</h1><p>{scope==='admin'?'Descarga los registros de cada sección del portal, incluidos sus estados e historial.':'Descarga tus acuses, avisos, contactos, solicitudes y los datos vinculados a tu perfil.'}</p></div><strong className="exports-total">{sections.length}<small>secciones</small></strong></header><div className="exports-note">CSV compatible con Excel y Google Sheets. La descarga conjunta entrega un ZIP con un CSV por sección. Los documentos, firmas y archivos conservan sus enlaces; sus imágenes no se incluyen dentro del CSV. Los avances de cuadernillos guardados únicamente en cada dispositivo no forman parte de estos registros.</div><div className="exports-controls"><label>Buscar sección<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Grupos, centros, usuarios, universidad, acuses…"/></label><div className="exports-buttons"><button disabled={loading||!!busy||!sections.length} className="exports-primary" onClick={()=>download(sections.map(s=>s.id),'zip')}>{busy==='zip'?'Preparando descarga…':'Descargar todas · ZIP'}</button><button disabled={!!busy||!selected.length} onClick={()=>download(selected,'zip')}>Descargar selección ({selected.length})</button></div><div className="exports-select"><button disabled={!!busy} onClick={()=>setSelected(old=>Array.from(new Set([...old,...filtered.map(s=>s.id)])))}>Seleccionar visibles</button><button disabled={!!busy||!selected.length} onClick={()=>setSelected([])}>Limpiar selección</button><span>{selected.length} seleccionadas</span></div></div>{error&&<div className="exports-error" role="alert">{error}{!sections.length&&<button onClick={load}>Reintentar</button>}</div>}{notice&&<p className="exports-success" role="status">{notice}</p>}{busy&&<p role="status" aria-live="polite">Preparando los registros. Las secciones grandes pueden tardar unos momentos.</p>}{loading?<p>Cargando secciones…</p>:groups.map(category=><section key={category} className="exports-group"><h2>{category}</h2>{filtered.filter(s=>s.category===category).map(s=><div className="exports-row" key={s.id}><label><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,s.id]:old.filter(id=>id!==s.id))}/><span>{s.title}</span></label><button disabled={!!busy} onClick={()=>download([s.id],'csv')}>{busy===s.id?'Preparando…':'Descargar CSV'}</button></div>)}</section>)}{!loading&&!error&&!filtered.length&&<p>No hay secciones que coincidan con tu búsqueda.</p>}</main><SubFooter/></>;
}
